name: tests
on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:

jobs:
  setup:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - name: unit tests
        run: go test -v ./pkg/... ./cmd/...

      - name: e2e tests
        run: ./scripts/run_e2e_tests.sh
